name       : spotifyd
version    : 0.3.5
release    : 4
source     :
    - https://github.com/Spotifyd/spotifyd/archive/refs/tags/v0.3.5.tar.gz : 59103f7097aa4e2ed960f1cc307ac8f4bdb2f0067aad664af32344aa8a972df7
homepage   : https://github.com/Spotifyd/spotifyd
license    : GPL-3.0-or-later
component  : multimedia.audio
networking : yes
summary    : Open source Spotify client running as a UNIX daemon
description: |
    Spotifyd streams music just like the official client, but is more lightweight and supports more platforms.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(libpulse)
    - cargo
build      : |
    cargo build --release --features pulseaudio_backend,rodio_backend,dbus_mpris,dbus_keyring
install    : |
    install -Dm00755 target/release/spotifyd $installdir/usr/bin/spotifyd
    install -Dm00644 contrib/spotifyd.service $installdir/usr/lib/systemd/user/spotifyd.service
check      : |
    cargo test
